%YAML:1.0

# MAIN
Init_Frame_Index: 120
USE_GT_DATA: 0
Calib_FX: 2666.67
Calib_FY: 2666.67
Calib_CX: 960
Calib_CY: 540
DIST_MASK_SIZE: 10
# Input/Output directories and Sets
LOG_Threshold :1
Input.Directory.LOG_DIR: "/home/qqh/output/ObjTrackLog/"
Input.Directory.Obj: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/openbox.obj"
Input.Directory.Video: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/"
Input.Directory.GroudTruth: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/poseGT.txt"


#View
CV_CIRCLE_RADIUS: 3
CV_LINE_P2NP: 1
#Optimize
MAX_ITERATIN_NUM: 8
THREHOLD_ENERGY: 170.0
DX_SIZE: 1.0
NX_LENGTH: 0.02
ENERGY_SIZE: 1.0
J_SIZE: 1e-2
LM_STEP: 10
INIT_LAMDA: 1
SIZE_A: 1
THREHOLD_DX: 1.0e17
USE_SOPHUS: 1
USE_MY_TRANSFORMATION: 1 
MAX_VALIAD_DISTANCE: 100
USE_PNP: 1
