%YAML:1.0

# MAIN
Init_Frame_Index: 0
USE_GT_DATA: 0
Calib_FX: 2666.67
Calib_FY: 2666.67
Calib_CX: 960
Calib_CY: 540
# Input/Output directories and Sets
LOG_Threshold :1
Output.Directory.LOG_DIR: "/home/qqh/output/ObjTrackLog/"
Input.Directory.Obj: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/openbox.obj"
Input.Directory.Video: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/"
Input.Directory.GroudTruth: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/poseGT.txt"


#View
CV_CIRCLE_RADIUS: 5
CV_LINE_P2NP: 0
CV_DRAW_FRAME: 1

#IMG
IMG_PYR_NUMBER: 5
IMG_DIST_MASK_SIZE: 5

#Optimize
DX_SIZE: 1.0
NX_LENGTH: 0.02
ENERGY_SIZE: 1.0
J_SIZE: 1e-2
LM_STEP: 10
INIT_LAMDA: 1
SIZE_A: 1
THREHOLD_DX: 1.0e17
USE_SOPHUS: 0
USE_MY_TRANSFORMATION: 1 
MAX_VALIAD_DISTANCE: 100
USE_PNP: 1
OPTIMIZER_MAX_ITERATIN_NUM: 15
OPTIMIZER_THREHOLD_ENERGY: 170.0
OPTIMIZER_NEASTP_THREHOLD: 200
OPTIMIZER_POINT_THREHOLD: 250
#Particle
PARTICLE_USE: 1
PARTICLE_ROTATION_GAUSSIAN_STD: 0.0005  #  rotation noise
PARTICLE_TRANSLATION_GAUSSIAN_STD: 0.005   # translation noise
PARTICLE_USE_AR: 1
PARTICLE_NoiseRateLow: 0.010
PARTICLE_NoiseRateHigh: 0.012
PARTICLE_NUM: 2
PARTICLE_ARParam: 0.1
