%YAML:1.0

# MAIN
Init_Frame_Index: 0
USE_GT_DATA: 0
Calib_FX: 2666.67
Calib_FY: 2666.67
Calib_CX: 960
Calib_CY: 540
DIST_MASK_SIZE: 5
# Input/Output directories and Sets
LOG_Threshold :1
Output.Directory.LOG_DIR: "/home/qqh/output/ObjTrackLog/"
Input.Directory.Obj: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/openbox.obj"
Input.Directory.Video: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/"
Input.Directory.GroudTruth: "/home/qqh/DataSets/3D Rigid Tracking from RGB Images Dataset/box/video1/poseGT.txt"


#View
CV_CIRCLE_RADIUS: 3
CV_LINE_P2NP: 0

#Optimize
MAX_ITERATIN_NUM: 15
THREHOLD_ENERGY: 170.0
DX_SIZE: 1.0
NX_LENGTH: 0.02
ENERGY_SIZE: 1.0
J_SIZE: 1e-2
LM_STEP: 10
INIT_LAMDA: 1
SIZE_A: 1
THREHOLD_DX: 1.0e17
USE_SOPHUS: 1
USE_MY_TRANSFORMATION: 0 
MAX_VALIAD_DISTANCE: 100
USE_PNP: 1

#Particle
PARTICLE_USE: 1
PARTICLE_ROTATION_GAUSSIAN_STD: 0.0005  #  rotation noise
PARTICLE_TRANSLATION_GAUSSIAN_STD: 0.005   # translation noise
PARTICLE_USE_AR: 0
PARTICLE_NoiseRateLow: 0.010
PARTICLE_NoiseRateHigh: 0.012
PARTICLE_NUM: 2
PARTICLE_ARParam: 0.1
#PARTICLE_STD_ROT: 0.01
#PARTICLE_STD_TRA: 0.01

